### ISSUE TITLE
Nouvelles autorisations google API

### ISSUE THREAD

**Issue by jjbertin** [nanostudio-org/nanogp2#1]
Bonjour,
Comme indiqué, j'ai créé une nouvelle autorisation API semblable à l'ancienne, mais commençant par nanogallery2gp, pour laquelle j'avais obtenu le consentement.
Actuellement, lorsque je lance l'URL : http://prod.chasse-autreches.xyz/nanogp2/authorize.php
j'obtiens le message suivant : 
400. C'est une erreur.
Erreur: invalid_request
Valeur de paramètre non valide pour redirect_uri: Autorité manquante: http: ///nanogp2/authorize.php
Mon dossier nanogp2 est bien présent chez l'hébergeur et son dossier config.php bien renseigné.
Je ne comprends pas l'origine de mon erreur.
Pouvez-vous m'aider. D'avance, merci.

**Comment by Kris-B** [comment]
Bonjour, les paramètres Google API Console pour `credentials` sont incorrects.
Merci de noter qu'il faut créer un nouveau projet dans l'API console, et ne pas modifier un ancien.

**Comment by jjbertin** [comment]
Bonjour,
Merci de votre réponse. J'ai recréé une nouvelle autorisation de A à Z, avec le même résultat d'échec. Je commets sans doute toujours la même erreur. Qu'entendez-vous exactement par "credentials".
D'avance merci de votre réponse.

**Comment by Ondrej2018** [comment]
Hello, 
I am getting same error. Followed all instructions from paragraph: Enable Google API - Google API Console, there was only once thing different: scopes for email, profile and openID were already somehow added in consent screen (are listed there but in grey color). Attaching error message: 

![error](https://user-images.githubusercontent.com/48549943/54345459-64d5d800-4643-11e9-8a79-ee9e486d8f45.png)

**Comment by Kris-B** [comment]
@Ondrej2018 
There's an issue in your Google Console API settings.
Please check the Authorized redirect URIs

**Comment by Kris-B** [comment]
@jjbertin  avez-vous créé des `credentials` dans la console google ?

**Comment by Ondrej2018** [comment]
> @Ondrej2018
> There's an issue in your Google Console API settings.
> Please check the Authorized redirect URIs

My setting is like this, is wrong?

![screen](https://user-images.githubusercontent.com/48549943/54346920-35749a80-4646-11e9-84d9-6a3a015af1d8.jpg)

**Comment by Kris-B** [comment]
@Ondrej2018 
I've just added the file `dist/check.php`
Please install it on your server and open it in your browser `https://www.jogin.cz/nanogp2/check.php`.
What is displayed?

**Comment by Ondrej2018** [comment]
Here it is: 

nanogp2 - installation check 
---------------------------- 

PHP version: 7.1.20 
Free disk space: 18110353408 
- CURL: 
Ok. 
- Write permissions: 
Ok. 
- URL authorization page: https:///nanogp2/check.php 
- URL request authorization: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=560443878274-8f0s1mc6l3kaef3uqvodsjcjri60t2ta.apps.googleusercontent.com&redirect_uri=https%3A%2F%2F%2Fnanogp2%2Fcheck.php&access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly+profile+email

**Comment by Kris-B** [comment]
I've updated `check.php`: can you update yours and re-run it ?

**Comment by Ondrej2018** [comment]
yes, here: 

nanogp2 - installation check 
---------------------------- 

PHP version: 7.1.20 
Free disk space: 18105982976 
- CURL: 
Ok. 
- Write permissions: 
Ok. 
- URL current page: https://www.jogin.cz/nanogp2/check.php 
- URL request: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=560443878274-8f0s1mc6l3kaef3uqvodsjcjri60t2ta.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fwww.jogin.cz%2Fnanogp2%2Fcheck.php&access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly+profile+email

**Comment by Ondrej2018** [comment]
looks better...

**Comment by Kris-B** [comment]
Thanks. It seems that there was a typo.
Please update `nanogp2.php` and `authorize.php` to v2.0.2

**Comment by Ondrej2018** [comment]
I confirm is working now, thanks for amazing work!

**Comment by Kris-B** [comment]
@Ondrej2018 thanks for your help !

**Comment by jjbertin** [comment]
J'ai mis à jour nanogp2 V2.0.2
J'ai obtenu les autorisations et la liste des albums dans users.
Merci de votre aide.

**Comment by Kris-B** [comment]
merci pour votre retour!
