### ISSUE TITLE
nanogp2 error: Cannot read property 'openSearch$startIndex' of undefined

### ISSUE THREAD

**Issue by ReversalRain** [nanostudio-org/nanogp2#2]
I am trying to use nanogp2 along with nanogallery2 and I have followed all steps describe on this Github page, authorization was successful, but when I opened my gallery page I saw the following error on Chrome (dev) console (shown further down) and nothing is shown on my gallery page. Below is the html markup on my gallery page. Any idea?

`<div id="nanogallery2" data-nanogallery2='{
    "kind":            "google2",
    "userID":          "<obscured>",
    "album":           "<obscured>",
    "google2URL":      "http://my.domain.com/nanogp2/nanogp2.php",
    "thumbnailHeight": 150,
    "thumbnailWidth":  "auto"
}'></div>`

jquery.nanogallery2.data_google2.min.js:10 Uncaught TypeError: Cannot read property 'openSearch$startIndex' of undefined
    at Object.success (jquery.nanogallery2.data_google2.min.js:10)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
(anonymous) @ jquery.nanogallery2.data_google2.min.js:10
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
k @ jquery-3.3.1.min.js:2
(anonymous) @ jquery-3.3.1.min.js:2
load (async)
send @ jquery-3.3.1.min.js:2
ajax @ jquery-3.3.1.min.js:2
w.(anonymous function) @ jquery-3.3.1.min.js:2
getJSON @ jquery-3.3.1.min.js:2
s @ jquery.nanogallery2.data_google2.min.js:10
i @ jquery.nanogallery2.data_google2.min.js:10
jQuery.nanogallery2.data_google2 @ jquery.nanogallery2.data_google2.min.js:10
ia @ jquery.nanogallery2.min.js:22
m @ jquery.nanogallery2.min.js:21
initiateGallery2 @ jquery.nanogallery2.min.js:25
d.init @ jquery.nanogallery2.min.js:25
a.nanogallery2 @ jquery.nanogallery2.min.js:25
(anonymous) @ jquery.nanogallery2.min.js:26
each @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
jQuery.fn.nanogallery2 @ jquery.nanogallery2.min.js:26
(anonymous) @ jquery.nanogallery2.min.js:41
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2

jquery.nanogallery2.min.js:25 Uncaught TypeError: Cannot read property 'baseEltID' of undefined
    at String.a.NanoConsoleLog (jquery.nanogallery2.min.js:25)
    at a.NanoAlert (jquery.nanogallery2.min.js:25)
    at jquery.nanogallery2.data_google2.min.js:10
a.NanoConsoleLog @ jquery.nanogallery2.min.js:25
a.NanoAlert @ jquery.nanogallery2.min.js:25
(anonymous) @ jquery.nanogallery2.data_google2.min.js:10
setTimeout (async)
i @ jquery.nanogallery2.data_google2.min.js:10
jQuery.nanogallery2.data_google2 @ jquery.nanogallery2.data_google2.min.js:10
ia @ jquery.nanogallery2.min.js:22
m @ jquery.nanogallery2.min.js:21
initiateGallery2 @ jquery.nanogallery2.min.js:25
d.init @ jquery.nanogallery2.min.js:25
a.nanogallery2 @ jquery.nanogallery2.min.js:25
(anonymous) @ jquery.nanogallery2.min.js:26
each @ jquery-3.3.1.min.js:2
each @ jquery-3.3.1.min.js:2
jQuery.fn.nanogallery2 @ jquery.nanogallery2.min.js:26
(anonymous) @ jquery.nanogallery2.min.js:41
l @ jquery-3.3.1.min.js:2
c @ jquery-3.3.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
fire @ jquery-3.3.1.min.js:2
u @ jquery-3.3.1.min.js:2
fireWith @ jquery-3.3.1.min.js:2
ready @ jquery-3.3.1.min.js:2
_ @ jquery-3.3.1.min.js:2

**Comment by Kris-B** [comment]
can you share the URL of a page where this issue can be reproduced?

**Comment by ReversalRain** [comment]
Thank you for your response. Sure, the URL of the gallery is: http://kiapa.orcawhale9.com/gallery

**Comment by Kris-B** [comment]
Your nanogp2 installation seems to be well configured (I can use it in my own page).

- You should only include `jquery.nanogallery2.min.js` (with the version number).
- `jquery.nanogallery2.data_google2.min.js`  should be removed.

```
<script src="https://unpkg.com/nanogallery2@2.4.1/dist/jquery.nanogallery2.min.js" type="text/javascript"></script>
```

Please note that package for v2.4.0 was corrupted - please use v2.4.1

**Comment by ReversalRain** [comment]
Sweet! Now I can see the content of my album. Thanks Kris. Another question: Can we browse albums on Google Photo using nanogallery2? Right now I have to specify the album ID on my gallery page and would like to show albums and click on an album to display the album content (which I know it is working now). Again, thank you for your quick response.

**Comment by Kris-B** [comment]
Juste remove the `album` parameter or set it to an empty string.

**Comment by ReversalRain** [comment]
Thanks Kris!!
