### ISSUE TITLE
Error 400 (Google Console API)

### ISSUE THREAD

**Issue by Gigiojam** [nanostudio-org/nanogp2#3]
I´m open this thread cause my issue not solved.

@Kris-B 
> There's an issue in your Google Console API settings.
> Please check the `Authorized redirect URIs`

The path must be "http://www.domain.com/nanogp2/authorize.php" or "http://www.domain.com/nanogp2/" ??

**Comment by Kris-B** [comment]
http://www.domain.com/nanogp2/authorize.php
and
https://www.domain.com/nanogp2/authorize.php

**Comment by Gigiojam** [comment]
Well, I try these two ways, but no success.

**Comment by Kris-B** [comment]
which error message do you have ?

**Comment by Gigiojam** [comment]
![captured](https://user-images.githubusercontent.com/36645299/54454063-641e6e00-4737-11e9-9fcc-d038a5876d49.jpg)

**Comment by Kris-B** [comment]
please download `nanogpo2.php` and `authorize.php` again, and overwrite your existing files.

**Comment by Gigiojam** [comment]
The issue was solved, but I get another error. See images:
(1) OK
![captured1](https://user-images.githubusercontent.com/36645299/54480005-394d1c00-4802-11e9-8ab3-3ecdeaefeb12.jpg)
(2) OK
![captured2](https://user-images.githubusercontent.com/36645299/54480006-423ded80-4802-11e9-8e1e-6d34110faa14.jpg)
(3) After step 3 I get this message again.
![captured3](https://user-images.githubusercontent.com/36645299/54480012-55e95400-4802-11e9-8013-e78ad1179413.jpg)

**Comment by Kris-B** [comment]
sorry, but I don't understand the brazilian language...

**Comment by Gigiojam** [comment]
Ok, the images was only to ilustrate the situation.
The images (3) is the end step... is english!
Do you know what means?

**Comment by Kris-B** [comment]
In the google console, what did you set for authorized redirect URL ?

**Comment by Gigiojam** [comment]
http://www.bandaomega3.com.br/nanogp2/authorize.php 
https://www.bandaomega3.com.br/nanogp2/authorize.php

**Comment by Kris-B** [comment]
did you se the scopes for the OAuth consent screen ?

**Comment by Gigiojam** [comment]
Sorry, I don´t unsderstand...

**Comment by Kris-B** [comment]
In the google console, did you create a OAuth consent screen ?

**Comment by Gigiojam** [comment]
Yes, I do.
The filled fileds: Application Name, Email and Authorized Domain

**Comment by Kris-B** [comment]
no scopes defined ?

**Comment by Gigiojam** [comment]
Yes... email, profile, openid

The Application Name  and Name ID client OAuth must be different?

**Comment by Kris-B** [comment]
Can you list here the permissions for all folders and files of your nanogp2 installation ?

**Comment by Kris-B** [comment]
do you have a `.htaccess` file in the `nanogp2` folder?

**Comment by Gigiojam** [comment]
All folders and files are 0755 permission.
Only in "admin" folder have a .htaccess file.

**Comment by Kris-B** [comment]
can you test with v2.0.4 ?

**Comment by Gigiojam** [comment]
OK, I will do

**Comment by Gigiojam** [comment]
I have uploaded "authorize.php" and "nanogp2.php" files v.2.0.4 but I get same error message.

**Comment by Kris-B** [comment]
@Gigiojam  please contact me directly : chr@brisbois.fr

**Comment by Kris-B** [comment]
ticket closed due to inactivity
