### ISSUE TITLE
Difficulté avec l'Autorisation

### ISSUE THREAD

**Issue by jjbertin** [nanostudio-org/nanogp2#4]
Bonjour,
J'ai bien récupéré mon ID utilisateur après affichage de _"Cette application n'est pas vérifiée"_.
J'ai également obtenu la liste des albums sur le serveur dans "users".
Je peux bien visionner les albums qui ont été traités selon ces nouveaux codes.
Le problème vient de la récupération des listes d'albums ; lorsque je demande une **nouvelle liste** (après avoir supprimé l'ancienne), j'ai ce message d'erreur : [{"nano_status":"error","nano_message":"Missing access token. Please grant authorization."}] et je ne peux plus poursuivre mes mises à jour.
D'avance merci de votre aide.

**Comment by Kris-B** [comment]
bonjour, vous avez donc juste supprimé le fichier `content.txt`, c'est bien ça ?

**Comment by jjbertin** [comment]
Bonjour, merci de me répondre. 
Non, car j'avais : 
admin > user > un dossier qui prend le nom de mon IDUser > Fichier .txt (que j'ai supprimé). 

Depuis, j'ai créé un nouveau projet nanogallery2gp-ACDC02 auquel j'ai donné les autorisations, mais les albums que j'avais déjà traité avec le projet nanogallery2gp-ACDC01 ne répondent plus. Je crains qu'ils aient changé d'IDAlbum ? 
Cordialement. 


----- Mail original -----

De: "Christophe Brisbois" <notifications@github.com> 
À: "nanostudio-org/nanogp2" <nanogp2@noreply.github.com> 
Cc: "jjbertin" <jeanjacques.bertin@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 15 Mars 2019 11:17:00 
Objet: Re: [nanostudio-org/nanogp2] Difficulté avec l'Autorisation (#4) 



bonjour, vous avez donc juste supprimé le fichier content.txt , c'est bien ça ?

**Comment by jjbertin** [comment]
Re-bonjour,
Je patauge ; j'ai repris l'opération de A à Z .
J'ai créé un nouveau projet dans google API
J'ai supprimé 'dist' sur mon serveur que j'ai de nouveau chargé issu du téléchargement.
J'ai obtenu l'autorisation avec mon 'IDuser'
J'ai mis à jour le 'config.php avec les nouveau codes obtenus.
Mais quand je veux voir un album sur mon site, rien ne s'affiche.
Je n'ose pas redemander la liste des albums 
(http://prod.chasse-autreches.xyz/nanogp2/nanogp2.php?nguserid=XXXX.......&report)
de peur d'obtenir un nouveau message d'erreur.
Est-ce là la source de mon erreur ?
D'avance merci de votre réponse.

**Comment by Kris-B** [comment]
L'appel de `...&report` ne devrait pas avoir d'impact. Lorsque nanogallery2 appelle nanogp2.php, les mêmes commandes sont envoyées à Google. Dans le premier cas, le résultat est écrit dans 1 fichier, dans le 2ème cas, le résultat est renvoyé à votre page.

J'ai lancé `http://prod.chasse-autreches.xyz/nanogp2/authorize.php?nguserid=115318255461408862217&report` depuis mon poste -> pas de message d'erreur.

Est-ce qu'un fichier `content.txt` a été créé ?

Par contre, je n'arrive pas interroger votre installation nanogp2 depuis avec nanogallery2, car vous n'êtes pas en https et chrome me bloque.

Est-ce que la page qui utilise nanogallery2 est sur le même serveur que nanogp2 ?
Pouvez-vous partager son URL ?

**Comment by jjbertin** [comment]
Merci de votre réponse.
Je ne vois pas de fichier content.txt, par contre je vois un fichier .htaccess qui n'y était pas ; je vous joint quatre copies d'écran concernant nanogp2, depuis votre intervention.
![ecran01](https://user-images.githubusercontent.com/34279286/54459869-34d42500-4768-11e9-813d-445df610320b.png)
![ecran02](https://user-images.githubusercontent.com/34279286/54459871-34d42500-4768-11e9-807a-7a25707bdcb7.png)
![ecran03](https://user-images.githubusercontent.com/34279286/54459872-34d42500-4768-11e9-8211-4d11160afc47.png)
![ecran04](https://user-images.githubusercontent.com/34279286/54459873-34d42500-4768-11e9-8bac-5330bfacbf26.png)
Url d'une page (qui fonctionnait hier soir) : http://prod.chasse-autreches.xyz/16-10-02-VUES-.htm
Merci vivement de votre aide.

**Comment by jjbertin** [comment]
Voici le message que je peux lire lorsque je lance la page en question :

_nanogallery2: Could not retrieve Google data. Error: error, Gateway Time-out readyState=4
getResponseHeader=function(e){var t;if(2===b){if(!c){c={};while(t=Tn.exec(a))c[t[1].toLowerCase()]=t[2]}t=c[e.toLowerCase()]}return null==t?null:t}
getAllResponseHeaders=function(){return 2===b?a:null}
setRequestHeader=function(e,t){var n=e.toLowerCase();return b||(e=v[n]=v[n]||e,y[e]=t),this}
overrideMimeType=function(e){return b||(p.mimeType=e),this}_

**Comment by jjbertin** [comment]
Désolé, erreur de ma part, le .htaccess figurait bien dès le début.

**Comment by Kris-B** [comment]
autant pour moi, il ne s'agit pas de `content.txt`, mais de `google_photos_data.txt`

combien d'images avez-vous dans votre album

**Comment by Kris-B** [comment]
et combien d'albums avez-vous ?

**Comment by jjbertin** [comment]
He non, pas de `google_photos_data.txt`
http://prod.chasse-autreches.xyz/16-10-02-VUES-.htm contient 49 images
Sur la liste que j'ai pu obtenir hier, j'ai 113 albums (chacun sur une page.htm distincte), mais je n'en ai passé que 12 aux nouveau code.
Ce que je ne comprends pas, c'est qu'hier j'ai pu obtenir cette liste, mais un événement dont j'ignore l'origine a annulé mes autorisations d'accès.
C'est la raison pour laquelle j'ai recréé un projet dans google api qui ne me donne pas les résultats escomptés.

**Comment by jjbertin** [comment]
Voici le message que j'obtiens lorsque je lance
`http://prod.chasse-autreches.xyz/nanogp2/nanogp2.php?guserid=115318255461408862217&report`
`{"nano_status":"error","nano_message":"Missing access token. Please grant authorization."}`

**Comment by Kris-B** [comment]
il y a une erreur de syntaxe dans votre URL : http://prod.chasse-autreches.xyz/nanogp2/nanogp2.php?nguserid=115318255461408862217&report

j'obtiens un time-out...

**Comment by jjbertin** [comment]
désolé, j'ai revérifié
`http://prod.chasse-autreches.xyz/nanogp2/nanogp2.php?nguserid=115318255461408862217&report`
mais je n'obtient rien, et je ne vois pas mon erreur.
J'espère que j'y verrai plus clair demain. Bonsoir et merci de votre aide.

**Comment by Kris-B** [comment]
merci de télécharger la nouvellle version de `nanogp2.php` -> j'ai optimisé la génération du rapport

**Comment by jjbertin** [comment]
Bonjour,
Merci de vos interventions.
J'ai téléchargé la nouvelle version nanogp2, j'ai pu rétablir l'accès à mes albums actualisés (après avoir révoqué l'autorisation API, puis rétabli celle-ci).

J'ai lancé l'URL `....&report` à partir de Chrome, mais j'obtient systématiquement ce message d'erreur `{"nano_status":"error","nano_message":"Missing access token. Please grant authorization."}`
J'ai de nouveau révoqué l'autorisation API, puis rétabli celle-ci.

Puis j'ai lancé `....&report` sur Firefox avec succès, mais avec ce message d'erreur à la seconde tentative, après avoir effacé le répertoire `IDUser` dans `user` : 
`nano_status | "error"
nano_message | "Missing access token. Please grant authorization."`
Conclusion : 
1) Il ne faut PAS EFFACER les répertoires et fichiers créés lors du premier lancement de `...&report`, sinon, il y a destruction de l'autorisation API.
2) Il semblerait que Chrome pose quelques problèmes (il faudrait poursuivre des tests, mais je suis un peu las !).
Merci vivement de votre précieuse aide qui m'a, enfin, permis d'accéder à mes albums.
Bien cordialement.

**Comment by Kris-B** [comment]
Effectivement, il ne faut jamais effacer les fichiers `profile.txt`, `token_a.txt` et `token_r.txt`: ils correspondent aux droits d'accès. En les supprimant, les authorisations sont perdues.
