### ISSUE TITLE
Wrong type of default pageSize value

### ISSUE THREAD

**Issue by guiguibzh** [nanostudio-org/nanogp2#8]
In nanogp2.php, when retrieving the list of albums, it seems that
`$request['pageSize'] = '50'` should be `$request['pageSize'] = 50`

**Comment by Kris-B** [comment]
Does it make any difference ? `$request` is converted in an URL-encoded query string

**Comment by guiguibzh** [comment]
I know it's weird but I wasn't able to access the album list with the current version, error 504, gateway timeout.

The API was called like that `https://photoslibrary.googleapis.com/v1/albums?access_token=xxx&pageSize="50"`, the double quotes  are problematic.

But without the quotes in nanogp2.php, it worked !

**Comment by Kris-B** [comment]
Interesting...
Fixed in v2.0.4, many thanks for reporting !
