### ISSUE TITLE
Gallery takes long to load.

### ISSUE THREAD

**Issue by db123v** [nanostudio-org/nanogp2#9]
Hi,

After updating my gallery to use nanogp2 the load time of the gallery seems to have drastically increased. The gallery used to load much quicker with the previous version. I also setup the gallery to just load the first 10 rows and have a more button to increase the performance, however it still takes long to load.
I did record the performace while the gallery was loading and noticed that their is multiple records for Recalculating style and applying style changes.

![2019-03-26_13h51_10](https://user-images.githubusercontent.com/36286515/54968313-520dbc80-4fce-11e9-8552-469b5abae657.png)
![2019-03-26_13h51_27](https://user-images.githubusercontent.com/36286515/54968316-54701680-4fce-11e9-906b-f694c9a09ece.png)
![2019-03-26_13h51_42](https://user-images.githubusercontent.com/36286515/54968318-5639da00-4fce-11e9-8f0a-755daeb26c8e.png)

Your help with this would be highly appreciated.

**Comment by Kris-B** [comment]
The only change is the use of the new Google API, which is much slower than the previous one.
Just loading the first 10 rows has no impact on loading time.
